# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
