# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_auto_20170307_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
