# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_auto_20170331_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
    ]
