# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_auto_20170331_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
