# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_transaction_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
