# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_transaction_item_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='cost_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflow.CostCenter'),
            preserve_default=False,
        ),
    ]
