# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
