# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 00:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_auto_20170419_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(11)999999999'. Up to 15 digits allowed.", regex='^\\(?\\d{2}?\\)?\\d{8,10}$')]),
        ),
    ]
