# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_auto_20170528_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
