# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_auto_20170615_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
