# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0015_item_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.CostCenter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Group'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Method'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Person'),
        ),
    ]
