# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_transaction_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(default=1),
        ),
    ]
