# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0019_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'AccountReceivable'), (2, 'AccountPayable'), (3, 'InventoryInput'), (4, 'InventoryOutput'), (5, 'Loan'), (6, 'Devolution')], default=1),
        ),
    ]
